### ISSUE TITLE
Can't view ipynb windows 10 vim 8

### ISSUE THREAD

**Issue by blayz3r** [goerz/ipynb_notedown.vim#2]
![ipynb](https://cloud.githubusercontent.com/assets/12205650/24075759/dfc332d4-0bf7-11e7-998b-56d48f0fa961.png)

I installed the plugin on windows but  all I get when I try to open a note book is some version of the screen above.Do you have any idea what could be causing this

**Comment by goerz** [comment]
I would imagine it's because the [system call to notedown](https://github.com/goerz/ipynb_notedown.vim/blob/master/plugin/ipynb_notedown.vim#L119) doesn't work (possibly because the output is redirected with `>` to a file). This plugin pretty much assumes a Unix environment (I don't have access to any Windows machines, so there'd be no way for me to test it). That being said, if someone has a patch that make this work on Windows, I'd be happy to accept pull requests.

**Comment by blayz3r** [comment]
Thanks, hopefully someone will come through .I have zero vim-script skills but am a very willing guinea pig for testing on windows.Can you put a gif or a pic  of what ipynb_notedown output looks like in a vim buffer.

**Comment by goerz** [comment]
Can you run [notedown](https://github.com/aaren/notedown) manually? Vim just edits the file that results from running the utility.

It looks like this:
![screenshot](https://cloud.githubusercontent.com/assets/112306/24077436/8fc3e3c4-0c23-11e7-8624-647ec6bf26c2.png)

instead of this:
![screenshot2](https://cloud.githubusercontent.com/assets/112306/24077437/9755a726-0c23-11e7-8b07-48dfc417a240.png)

**Comment by blayz3r** [comment]
Yes notedown works fine.I meant adding the images as part of the readme to make it clear what the plugin does.
